name: Build-a-Bob
on: [push, workflow_dispatch]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Say hi
        run: echo 你好
      - name: Say bye
        run: echo 再见
      - name: Branch
        run: |
          echo [debug] ${{ github.server_url }}/${{ github.repository }}
          echo [debug] ${{ github.ref }}
          echo [debug] ${{ github.ref_name }}
