on:
  push:
    branches:
      - release-please--branches--main

# Modify the default permissions granted to GITHUB_TOKEN
# see: https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
permissions:
  contents: write
  packages: read

jobs:
  release-please-pr-updater:
    name: release-please-pr-updater
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3
        with:
          ref: release-please--branches--main

      - name: 😻 Setup node
          uses: actions/setup-node@v3
          with:
            node-version-file: '.node-version'
            registry-url: 'https://npm.pkg.github.com/'

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      # This step only executes when a Release PR has been created or updated.
      # It will run the `npm install` command and commit any changes in the
      # package-lock.json file. Ideally, release-please would update this file itself
      # and we could remove conditional logic from the release workflow
      - name: Update package-lock.json
        if: ${{ steps.check_release_pr.outputs.exists }}
        run: |
          npm install
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add package-lock.json
          git diff-index --quiet HEAD || git commit -m "chore: update package-lock.json" -m "running npm install in github release workflow to update package-lock.json"
          git push